services:
  wiremock:
    image: holomekc/wiremock-gui:latest
    environment:
      WIREMOCK_OPTIONS: "--verbose"
    ports:
      - "8080:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
